SomeAspProject/Models/ErrorViewModel.cs
using System;

namespace SomeAspProject.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SomeAspProject/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SomeAspProject.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SomeAspProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SomeAspProject/Controllers/SqlController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using System.Text.RegularExpressions;
using SomeAspProject.Services.Database;

namespace SomeAspProject.Controllers
{
    public class SqlController : Controller
    {
        private readonly IDatabaseService _database;

        public SqlController(IDatabaseService database)
        {
            _database = database;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> SendRequest(string req)
        {
            var result = await _database.SendRequestAsync(req);
            ViewBag.SqlRequest = req;
            return View(nameof(Index), result);
        }
    }
}

SomeAspProject/Views/Home/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Hellow there.</h1>
    <p>Want some data?</p>
    <p>Get it <a asp-controller="Sql" asp-action="Index">here</a>. If you can.</p>
</div>

SomeAspProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SomeAspProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SomeAspProject</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SomeAspProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SomeAspProject/Views/Sql/Index.cshtml
@using SomeAspProject.Services.Database;
@model DatabaseRequestResult
@{
    ViewData["Title"] = "Sql Page";
}
<h1 class="display-4">
    Sql request sending
</h1>
<small class="text-muted">Send your request now!</small>
<form>
    <div class="form-row">
        <div class="col-auto">
            <label class="col-form-label font-weight-bolder" for="req">Sql request:</label>
        </div>

        <div class="col">
            <input id="req" name="req" value="@ViewBag.SqlRequest" class="form-control" placeholder="select * from Orders" required />
        </div>

        <div class="col-auto">
            <button type="submit" asp-controller="Sql" asp-action="SendRequest" class="btn btn-primary">Send request</button>
        </div>
    </div>

    @if (Model != null)
    {
        <div class="form-group mt-3">
            @if (Model.RecordsAffected == -1)
            {
                if (Model.IsSuccess)
                {
                    if (Model.Rows.Count > 0)
                    {
                        <table class="table table-bordered table-hover" cellspacing='0'>
                            <thead class="thead-dark">
                                <tr>
                                    @foreach (var th in Model.Headers)
                                    {
                                        <th>@th.Name</th>
                                    }
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var tr in Model.Rows)
                                {
                                    <tr>
                                        @foreach (var td in tr)
                                        {
                                            <td>@td</td>
                                        }
                                    </tr>
                                }
                            </tbody>
                        </table>
                    }
                    else
                    {
                        <div class="text-success text-center border border-success p-4">
                            <text>Success</text>
                        </div>
                    }
                }
                else
                {
                    <div class="text-danger text-center border border-danger p-4">
                        <text>Unexpected error:  @Model.InnerException.Message</text>
                    </div>
                }
            }
            else
            {
                <div class="text-success text-center border border-success p-4">
                    <text>Rows updated: @Model.RecordsAffected</text>
                </div>
            }

        </div>
    }
</form>